export const defaultSettings = {
  EvB: {
    topText: 'EXCITED',
    bottomText: 'BORED',
    color: '#b83f3a',
    benchmark: 0.4,
    topEmoji: 'excited',
    bottomEmoji: 'bored',
    minValue: -50,
    maxValue: 50,
  },
  FvP: {
    topText: 'FULFILLED',
    bottomText: 'POINTLESS',
    color: '#e69846',
    benchmark: 0.4,
    topEmoji: 'fulfilled',
    bottomEmoji: 'pointless',
    minValue: -50,
    maxValue: 50,
  },
  PvE: {
    topText: 'PROUD',
    bottomText: 'EMBARRASSED',
    color: '#f0ca00',
    benchmark: 0.4,
    topEmoji: 'proud',
    bottomEmoji: 'embarrassed',
    minValue: -50,
    maxValue: 50,
  },
  VvS: {
    topText: 'VALUABLE',
    bottomText: 'STUCK',
    color: '#9acea8',
    benchmark: 0.4,
    topEmoji: 'valuable',
    bottomEmoji: 'stuck',
    minValue: -50,
    maxValue: 50,
  },
  RvD: {
    topText: 'REWARDED',
    bottomText: 'DISDAINED',
    color: '#a6c6e4',
    benchmark: 0.4,
    topEmoji: 'rewarded',
    bottomEmoji: 'disdained',
    minValue: -50,
    maxValue: 50,
  },
  SvT: {
    topText: 'SAFE',
    bottomText: 'THREATENED',
    color: '#975ba1',
    benchmark: 0.4,
    topEmoji: 'safe',
    bottomEmoji: 'threatened',
    minValue: -50,
    maxValue: 50,
  },
  CvD: {
    topText: 'CONTENTED',
    bottomText: 'DESPONDENT',
    color: '#bd619a',
    benchmark: 0.4,
    topEmoji: 'contented',
    bottomEmoji: 'despondent',
    minValue: -50,
    maxValue: 50,
  },
};
