export const defaultSettings = {
  excitement: {
    topText: 'EXCITED',
    bottomText: 'BORED',
    color: '#b83f3a',
    benchmark: 0.4,
    topEmoji: 'excited',
    bottomEmoji: 'bored',
    minValue: -50,
    maxValue: 50,
  },
  fulfillment: {
    topText: 'FULFILLED',
    bottomText: 'POINTLESS',
    color: '#e69846',
    benchmark: 0.4,
    topEmoji: 'fulfilled',
    bottomEmoji: 'pointless',
    minValue: -50,
    maxValue: 50,
  },
  selfesteem: {
    topText: 'PROUD',
    bottomText: 'EMBARASSED',
    color: '#f0ca00',
    benchmark: 0.4,
    topEmoji: 'proud',
    bottomEmoji: 'embarrassed',
    minValue: -50,
    maxValue: 50,
  },
  progress: {
    topText: 'VALUABLE',
    bottomText: 'STUCK',
    color: '#9acea8',
    benchmark: 0.4,
    topEmoji: 'valuable',
    bottomEmoji: 'stuck',
    minValue: -50,
    maxValue: 50,
  },
  reward: {
    topText: 'REWARDED',
    bottomText: 'DISDAINED',
    color: '#a6c6e4',
    benchmark: 0.4,
    topEmoji: 'rewarded',
    bottomEmoji: 'disdained',
    minValue: -50,
    maxValue: 50,
  },
  security: {
    topText: 'SAFE',
    bottomText: 'THREATENED',
    color: '#975ba1',
    benchmark: 0.4,
    topEmoji: 'safe',
    bottomEmoji: 'threatened',
    minValue: -50,
    maxValue: 50,
  },
  contentment: {
    topText: 'CONTENDED',
    bottomText: 'DESPONDENT',
    color: '#bd619a',
    benchmark: 0.4,
    topEmoji: 'contended',
    bottomEmoji: 'despondent',
    minValue: -50,
    maxValue: 50,
  },
};
